version: 0.2

env:
  shell: bash
  variables:
    CONTAINER_NAME: "appcontainer"
    TASK_FAMILY: "app-fargate-task"
    TASK_DEFINITION_ARN: ""

phases:
  install:
    commands:
      - echo Instalando dependencias...
      - pip install -r requirements.txt

      - echo Instalando jq...
      - if command -v yum &> /dev/null; then
          yum install -y jq;
        elif command -v apt-get &> /dev/null; then
          apt-get update && apt-get install -y jq;
        else
          echo "No se pudo determinar el gestor de paquetes (yum/apt-get). Instala jq manualmente.";
          exit 1;
        fi
      - jq --version

  pre_build:
    commands:
      - echo Ejecutando pruebas unitarias...
      - pytest -v src/test/test.py --maxfail=1 --disable-warnings -q || (echo "Las pruebas fallaron" && exit 1)

      - echo Iniciando sesión en Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI

      - echo Calculando IMAGE_TAG...
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - export IMAGE_TAG
      - echo IMAGE_TAG=$IMAGE_TAG
      - echo ECR_REPO_URI=$ECR_REPO_URI

  build:
    commands:
      - echo Construyendo imagen Docker...
      - docker build -t $ECR_REPO_URI:$IMAGE_TAG .
      - docker tag $ECR_REPO_URI:$IMAGE_TAG $ECR_REPO_URI:latest

      - echo Obteniendo ARNs de los roles IAM...
      - EXECUTION_ROLE_ARN=$(aws iam get-role --role-name ecsTaskExecutionRole --query 'Role.Arn' --output text)
      - TASK_ROLE_ARN=$(aws iam get-role --role-name ecsTaskExecutionRole --query 'Role.Arn' --output text)
      - echo "EXECUTION_ROLE_ARN=$EXECUTION_ROLE_ARN"
      - echo "TASK_ROLE_ARN=$TASK_ROLE_ARN"

      - echo Configurando variables de entorno de la base de datos...
      - export DB_HOST=${DB_HOST}
      - export DB_NAME=${DB_NAME}
      - export DB_USER=${DB_USER}
      - export DB_PASSWORD=${DB_PASSWORD}

      - echo Creando taskdef.json para ECS Fargate...
      - |
        cat > taskdef.json <<EOF
        {
          "family": "$TASK_FAMILY",
          "networkMode": "awsvpc",
          "requiresCompatibilities": ["FARGATE"],
          "cpu": "1024",
          "memory": "3072",
          "executionRoleArn": "$EXECUTION_ROLE_ARN",
          "taskRoleArn": "$TASK_ROLE_ARN",
          "containerDefinitions": [
            {
              "name": "$CONTAINER_NAME",
              "image": "$ECR_REPO_URI:$IMAGE_TAG",
              "essential": true,
              "cpu": 10,
              "memory": 256,
              "portMappings": [
                {
                  "containerPort": 8000,
                  "hostPort": 8000,
                  "protocol": "tcp"
                }
              ],
              "environment": [
                {
                  "name": "DB_HOST",
                  "value": "${DB_HOST}"
                },
                {
                  "name": "DB_NAME",
                  "value": "${DB_NAME}"
                },
                {
                  "name": "DB_USER",
                  "value": "${DB_USER}"
                },
                {
                  "name": "DB_PASSWORD",
                  "value": "${DB_PASSWORD}"
                }
              ],
              "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                  "awslogs-group": "/ecs/${TASK_FAMILY}",
                  "awslogs-region": "${AWS_DEFAULT_REGION}",
                  "awslogs-stream-prefix": "ecs"
                }
              }
            }
          ]
        }
        EOF

      - echo Validando taskdef.json generado...
      - cat taskdef.json
      - echo Validando JSON syntax...
      - jq empty taskdef.json

      - echo Registrando nueva definición de tarea en ECS...
      - TASK_DEFINITION_ARN=$(aws ecs register-task-definition \
          --cli-input-json file://taskdef.json \
          --query "taskDefinition.taskDefinitionArn" \
          --output text)
      - export TASK_DEFINITION_ARN
      - echo "TASK_DEFINITION_ARN=$TASK_DEFINITION_ARN"

      - echo Verificando que el ARN fue obtenido correctamente...
      - |
        if [ -z "$TASK_DEFINITION_ARN" ] || [ "$TASK_DEFINITION_ARN" = "None" ]; then
          echo "ERROR: No se pudo registrar la task definition"
          exit 1
        fi

      - echo Creando appspec.yml para CodeDeploy ECS...
      - |
        cat > appspec.yml <<EOF
        version: 0.0
        Resources:
          - TargetService:
              Type: AWS::ECS::Service
              Properties:
                TaskDefinition: "$TASK_DEFINITION_ARN"
                LoadBalancerInfo:
                  ContainerName: "$CONTAINER_NAME"
                  ContainerPort: 8000
        Hooks:
          - BeforeInstall:
              location: scripts/before_install.sh
              timeout: 300
              runas: root
          - AfterInstall:
              location: scripts/after_install.sh
              timeout: 300
              runas: root
        EOF

      - echo Creando scripts de hooks para CodeDeploy...
      - |
        mkdir -p scripts
        cat > scripts/before_install.sh <<'EOL'
        #!/bin/bash
        echo "Ejecutando hook BeforeInstall"
        # Aquí puedes agregar acciones previas, como backups, limpieza, etc.
        EOL

        cat > scripts/after_install.sh <<'EOL'
        #!/bin/bash
        echo "Ejecutando hook AfterInstall"
        # Aquí puedes agregar acciones posteriores, como migraciones, validaciones, etc.
        EOL

        chmod +x scripts/*.sh

      - echo Mostrando contenido generado de appspec.yml
      - cat appspec.yml

      - echo Empaquetando artefactos para CodeDeploy ECS...
      - mkdir -p output
      - cp taskdef.json output/
      - cp appspec.yml output/
      - cp -r scripts output/

  post_build:
    commands:
      - echo Subiendo imagen a ECR...
      - docker push $ECR_REPO_URI:$IMAGE_TAG

artifacts:
  files:
    - output/**/*
  discard-paths: yes
